### ISSUE TITLE
/settings + "Authorize Character" use a wrong redirect_uri

### ISSUE THREAD

**Issue by FroutSarain** [bokoboshahni/eve-indy-watch#148]
On my system, it uses `redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Feve%2Fcallback`when it should be using 0.0.0.0 instead - I don't have the issue with a regular login

**Comment by bokoboshahni** [comment]
Do you have `ESI_REDIRECT_URI` set in your `.env` file by chance? This is a legacy thing that actually needs to be removed and derived from Rails own `routes.default_url_options` configuration instead of sourced from an environment variable. If you set that environment variable to `http://0.0.0.0:3000/auth/eve/callback` though it should work.
